In [1]:
import numpy

In [ ]:
import numpy as np 

arr = np.array([1,2,3])


In [3]:
print(arr)

[1 2 3]


In [4]:
import numpy as np

print(np.__version__)

1.25.2


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
arr2 = np.array((1,2,3,4))

In [10]:
print(arr2)
print(type(arr2))

[1 2 3 4]
<class 'numpy.ndarray'>


In [11]:
import numpy as np

arr = np.array(42)

print(arr)

42


In [12]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [13]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [14]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])


2


In [22]:
arr3 = np.array((9,8,7,6,5,4))

print(arr3)

print(type(arr3))

[9 8 7 6 5 4]
<class 'numpy.ndarray'>


In [13]:
import numpy as np

a = np.array([1,2,3,5])
b = np.array([[9,9,8,4], [3,42,5,2]])
c = a+b


print(a.ndim)
print(b.ndim)
print(b.dtype)
print(a.dtype)
print(a.shape)
print(b.shape)


1
2
int32
int32
(4,)
(2, 4)


In [18]:
import numpy as np
c = np.zeros((2,3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
d = np.ones((2,2))
print(d)

[[1. 1.]
 [1. 1.]]


In [22]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [23]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [24]:
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


In [30]:
z = np.array([1,2,3,4,5,6,7,8,10])

z.reshape(3,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [37]:
import numpy as np

a = np.arange(1,11)

# 1. Print even numbers
# 2. Square all elements
# 3. Find mean
# 4. Reshape into (2,5)

#1 
b = np.arange(2,11,2)
print(b)

#2 
c = a**2
print(c)

[ 2  4  6  8 10]
[  1   4   9  16  25  36  49  64  81 100]


In [38]:
a.mean()

5.5

In [40]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [74]:
# fancy indexing 

import numpy as np

a = np.array([10, 20, 30, 40, 50])

idx = [0, 2, 4]
print(a[idx])   # [10 30 50]

[10 30 50]


In [ ]:
import numpy as np

a = np.array([10, 20, 30, 40, 50 , 60 , 70 ,80])

idx = [0, 2, 6]
print(a[idx])   # [10 30 50]

[10 30 70]


In [76]:
idx2 = [2,6,7]
print(a[idx2])

[30 70 80]


In [ ]:
a = np.array([[1,2],
              [3,4],
              [5,6]])

row = [0,2]
print(a[row])

[[1 2]
 [5 6]]


In [80]:
# Boolean masking

a = np.array([10, 20, 30, 40])

mask = a > 20
print(mask)     # [False False True True]

print(a[mask])  # [30 40]

[False False  True  True]
[30 40]


In [81]:
a[(a > 10) & (a < 40)]

array([20, 30])

In [82]:
a = np.array([[1,2],
              [3,4]])

b = np.array([[5,6],
              [7,8]])

np.dot(a, b)

array([[19, 22],
       [43, 50]])

In [83]:
np.linalg.det(a)

-2.0000000000000004